name: responsive_sliding_drawer
description: "A responsive sliding drawer widget inspired by the official ChatGPT Android app"
version: 1.5.1
homepage: https://github.com/hruzgar/flutter_responsive_sliding_drawer

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
